### ISSUE TITLE
Add url to description

### ISSUE THREAD

**Issue by CWWhitney** [nafsi20/rice-farming-with-crop-rotation#10]
Use the native git tools to host the url for your report 

http://htmlpreview.github.io/?https://github.com/nafsi20/rice-farming-with-crop-rotation/blob/main/Rice-farm-and-crop-rotation.html

**Comment by noviriasyifaunnafsi** [comment]
Thank you, but I'm so sorry, I think I can't understand your instruction correctly.

I have tried to edit the setting in the github page section to get the url from this repo: 
https://nafsi20.github.io/rice-farming-with-crop-rotation/ 
but it shows the readme file, not the html file that we use as our report which attached in the repository (so i think maybe this is not what you mean?)

and also, I'm sorry that I just updated the HTML file because it was not updated yet as we have shared on slack group.
So here is the correct one:
https://htmlpreview.github.io/?https://github.com/nafsi20/rice-farming-with-crop-rotation/blob/main/Rice-farm-with-crop-rotation.html --> the same as we have shared on slack group.
I put this url to the description of this repository.

Please kindly let us know what actually we should do for this. 
I'm really sorry for the inconvenience.
Thanks in advance

**Comment by CWWhitney** [comment]
All is well. You have addressed it enough.
